- hosts: localhost
  become: true
  tasks:
  - name: update repositories
    apt: update_cache=yes
    changed_when: False
  - name: Install tmux
    apt: name=tmux
  - name: Install bincat
    apt: name=bincat
  - name: Install neovim
    get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        dest: /usr/local/bin/neovim
        mode: '0755'
